### PR TITLE
Kodi: update patch to include bugfixes

### PR DESCRIPTION
**Pull request by garbear**
Includes the following fixes:

* Small optimization when constructing CAESinkSteamLinkStream::AudioPacket
* Remove unused member variable CAESinkSteamLinkStream::m_bInVideo
* Fix constant audio offset of 250ms in video
* Fix race condition when flusing audio stream

### CODE REVIEW

**Comment by garbear** [comment]
Oops, it looks like this got dropped from master (LFS troubles I'm guessing?). Should I resubmit?

**Comment by parkerlreed** [comment]
Yeah I noticed on the reset that doing a fresh clone + LFS pull didn't actually pull any files from LFS. 

@slouken mentioned the reset here http://steamcommunity.com/app/353380/discussions/1/133256240742227714/

**Comment by garbear** [comment]
cool thanks for pointing that out

**Comment by slouken** [comment]
It's not in the history, but these changes are in the master repo.

**Pull request merged**
