### PR TITLE
Kodi fixes

### PR DESCRIPTION
**Pull request by ezelkow1**
with these changes i could do a full kodi build in my VM

I am completely unsure if these are correct fixes but throwing them out there so people can take a look and play with them, Im still waiting on my link hardware to test.

Im unsure about removing the sdl portion of joystick settings. It looks like it doesnt exist in xbmc anymore but then I dont know if that means it now needs to be added back, but we are disabling joystick anyway.

For the system header one of the steam devs would really have to look at that first. I dont know if its completely safe to remove that header file include, if thats going to break anything else. I have seen on various forums the exact same issue/error that I hit and why I removed it:
sys/xattr.h:31:3: error: expected identifier before numeric constant
   XATTR_CREATE = 1, /* set value, fail if attr already exists. */

It appears that in some glibc/eglibc they changed the define and so that conflicts with this one. So I guess theres no other software being built that pulls in xattr or the original header that brought in the issue compatibility.h

### CODE REVIEW

**Comment by Tele42** [comment]
There are serious performance repercussions for disabling neon and gles on arm. All you are doing here is breaking support on arm devices.

**Comment by ezelkow1** [comment]
It's not actually disabling those, it's pulling them out of the patch, pretty sure they are on by default

**Comment by ezelkow1** [comment]
I can add it back in though to ease confusion

**Comment by jonesmz** [comment]
I can confirm that without this pullrequest the ./build_steamlink.h script fails right away when applying the patch, with this pullrequest the patching process succeeds, and the build actually starts.

**Comment by ezelkow1** [comment]
Im also not sure if something changed on the kodi side or not. So when I first did the patch ~week ago I could actually complete a build fine. However in the past couple days something changed wrt to the pkgconfig setup.  It seems like the samba pkgconfig file isnt being copied, so while all the dependencies will build and be placed properly, the xbmc configure script wont pick up the samba lib or location properly

Manually copying the .pc file got around that, so I could test the final build, which still didnt work (this was after manually setting up pulse8.0).  Errors in setting up the windowing.  So kodi still wont fully launch

**Comment by jonesmz** [comment]
On my machine (Gentoo, x86_64 Hardened nomultilib), it's failing to compile something in the SDL code. I didn't look too closely at it, since I ran it really late at night, but I'm going to poke at it again today and see if I can have any luck.

**Comment by jonesmz** [comment]
Maybe it would be wise to pick a specific commit out of the kodi / xmbc git repository that does build?

**Comment by ezelkow1** [comment]
yea probably, I havent really looked in to how its choosing the kodi rev to pull yet

**Comment by jonesmz** [comment]
if [ ! -d "${SRC}" ]; then
	git clone https://github.com/xbmc/xbmc.git "${SRC}" || exit 1
	rm -f "${TOP}/.patch-applied"
fi

Looks like it just goes straight for the latest commit in master.

I'll try to find a revision that works reliably.

**Comment by jonesmz** [comment]
I'm still waiting for the build to complete, but have gotten much farther than last time.

If you change 
git checkout .

to

git checkout 85ade678e1e53ba19a862a165a81db31997de496

in build_steamlink.sh, it seems like it'll compile

**Comment by jonesmz** [comment]
Ah, bummer. It just finished and errored out:

make -C libsdl2
make[1]: Entering directory '/home/jonesmz/steamlink-sdk/examples/kodi/kodi-src/tools/depends/target/libsdl2'
make -C armv7a-cros-linux-gnueabi
make[2]: Entering directory '/home/jonesmz/steamlink-sdk/examples/kodi/kodi-src/tools/depends/target/libsdl2/armv7a-cros-linux-gnueabi'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/home/jonesmz/steamlink-sdk/examples/kodi/kodi-src/tools/depends/target/libsdl2/armv7a-cros-linux-gnueabi'
Makefile:30: recipe for target 'armv7a-cros-linux-gnueabi/build/.libs/libSDL2.a' failed
make[1]: *** [armv7a-cros-linux-gnueabi/build/.libs/libSDL2.a] Error 2
make[1]: Leaving directory '/home/jonesmz/steamlink-sdk/examples/kodi/kodi-src/tools/depends/target/libsdl2'
Makefile:113: recipe for target 'libsdl2' failed
make: *** [libsdl2] Error 2
make: Leaving directory '/home/jonesmz/steamlink-sdk/examples/kodi/kodi-src/tools/depends/target'

**Comment by ezelkow1** [comment]
hmm, Im still not having an sdl build issue. I do probably have the sdl-dev headers installed on my box but I wouldnt think that would make a difference in this case since it looks like yours isnt even grabbing/unpacking the sdl2 lib to build

Do you have curl and curl-dev installed on your machine? Im pretty sure I needed curldev since if you scroll up theres a build err before that about curl

**Comment by jonesmz** [comment]
I went in and ran ./configure (with appropriate options) manually for sdl, and now things are moving farther.

**Comment by ezelkow1** [comment]
So back to where I was with manually copying in pulse-8. Dont forget you also have to edit the build_steamlink.sh to use pulseaudio 8 instead of 6

So I can see kodi starting up, enumerates pulse devices, interestingly streamTypes says no passsthrough capabilities, that would definitely be nice to enable for kodi usage so we can do passthru of various audio formats.
Then continues on initializing and still fails at the window system:
00:02:08 T:3002621952   ERROR: InitWindowSystem: Could not initialize
00:02:08 T:3002621952   FATAL: CApplication::Create: Unable to init windowing system

**Comment by jonesmz** [comment]
Changing build_steamlink to use pulseaudio 8 instead of 6 causes a linker error on my machine...

I did get a full build with pulse 6, and I tried it out on my steamlink, but it just goes back to the main screen.

Setting up ssh and debugging on it now to take a look.

**Comment by ezelkow1** [comment]
hmm, might need to update your git revision, I updated my fork to the latest so it pulled in pulse8 into the rootfs. So without that you would still have 6 probably

Im pretty sure that was one issue is that you'll see if you try to launch it manually it will fail since its built against pulse6 which wont exist on the link anymore, so you have to use the new rootfs.

**Comment by jonesmz** [comment]
I was originally using the pull request branch that github auto generates inside of this main repository.

I'm rebuilding against your version now.

**Comment by jonesmz** [comment]
The most recent error I ran into was this:

checking for X11/extensions/Xext.h... no
configure: error:
*** Missing Xext.h, maybe you need to install the libxext-dev package?


I get that while configuring sdl. This is probably why I was having problems with it before.

I do have /usr/include/X11/extensions/Xext.h, but it shouldn't be searching my local system.

Think maybe the configuration options are bad?

This is what the configure line is:
./configure --prefix=/home/jonesmz/steamlink-sdk/kodi-deps/armv7a-cros-linux-gnueabi --disable-video-directfb

Maybe it needs something like --disable-video-x11 as well?

**Comment by ezelkow1** [comment]
yea i remember seeing x11 disabled in the automatic build output.  You might want to run the build script first and see what configure options are being used for your own build

**Comment by jonesmz** [comment]
Do you mean my steamlink-kodi build? I've got the whole build output saved.

I'll check and see what's causing it to not disable x11.

**Comment by ezelkow1** [comment]
Right, just compare the output from the build_steamlink.sh output and your own at the point where its doing the sdl config.  The one from the script should be the proper options.  Im still not sure whats different though where your having issues with that build script, besides the samba issue and having to change it to pulse8 I can use the build script all the way through

**Comment by jonesmz** [comment]
It's probably an OS level difference. Are you using Ubuntu / Debian? Maybe I should spin up a virtual machine.

**Comment by ezelkow1** [comment]
yea Id figure its a distro/installed packages issue. Im running a linux mint VM, which is basically ubuntu. I found almost all of my build issues were resolved by installing various dev libs and tools that werent installed by default in the VM

**Comment by Moredread** [comment]
I also had various problems in the past on my Arch machine, when it seemed fine for others. I haven't really investigated that further though.

What distro are you using, @jonesmz?

**Comment by jonesmz** [comment]
Gentoo, x86_64, Hardened, nomultilib

**Comment by LeBlue** [comment]
I managed to manually compile the kodi example and get it running on the steamlink (build 518), steamlink-sdk commit 59d94cc.
Roughly the steps I took to get kodi to build and run:

- used kodi.patch.txt from #26 
- steps mentioned here: 
- add `--disable-x11` to sdl2 configure options and manually call `make` that calls `./configure` with appropriate flags, `-B` to force rebuild, since there seems to be a prerequisite missing:
```
cd steamlink-sdk/examples/kodi/kodi-src/tools/depends/target/libsdl2/
make -B armv7a-cros-linux-gnueabi/build/.libs/libSDL2.a
touch .installed-armv7a-cros-linux-gnueabi
```
- copying the `.pc` files for the samba libraries: 
```
cp examples/kodi/kodi-src/tools/depends/target/samba-gplv3/armv7a-cros-linux-gnueabi/source3/pkgconfig/*.pc kodi-deps/armv7a-cros-linux-gnueabi/lib/pkgconfig/
```
- replace `-lpulsecommon-6.0` with `-lpulsecommon-8.0` in `build_steamlink.sh`
- commented out that failing `#include <xattr.h>` line in `rootfs/usr/include/sys/capability.h
`.

Up to here kodi would build but fail to initialize the windowing system. It seems it can't find the framebuffer device. Should there be one on the steamlink? If not, why build with -DEGL_API_FB? Am I missing some kernel modules/libraries?

What seems to work though is to tell kodi to use **SDL2** lib for rendering by adding 
```
PKG_CHECK_MODULES([SDL],  [sdl2 >= 2.0],
  [INCLUDES="$INCLUDES"; LIBS="$LIBS"],
  AC_MSG_ERROR($missing_library))
AC_DEFINE([HAVE_SDL],[1],["Define to 1 if using sdl"])
AC_DEFINE([HAVE_SDL_VERSION],[2],["SDL major version"])
```
to kodi's `configure.ac` and regenerating the `configure` script. **This will only work with the SDL2 library/headers that are included in the `rootfs`**, not the one built as kodi dependency (I just removed it completely). That one is missing some Vivante driver symbols (e.g. `SDL_SYSWM_VIVANTE`) in its header and compilation will fail.

Since the kodi.patch introduces some SDL video code, is SDL2 the intended rendering lib for kodi? Why is SDL2 build?

This got me a smooth running kodi UI and video, still no sound though (see. #31)

**Comment by ezelkow1** [comment]
nice thanks, Ill have to give this a try.  Just redid my VM so Ill have to start from scratch anyway

I dont know on the any of the SDL stuff.  Im not a graphics person but that was all added originally by slouken in his original patches. Id think he'd know what to do since Im pretty sure he wrote SDL :) Just hoping he stops by the github some time

**Comment by ezelkow1** [comment]
checked in a few more fixes to hopefully make peoples lives easier.  Changed the build script so it pulls pulse8 and copies the samba PC files.  Also added in the SDL configure.ac change as well as a change for the FFMPEG lib in the patch.  Looks like the more recent kodi checkins changes the location in the configure.ac and it was breaking for me when searching for libavcodec.a

Right now Im  just stuck at the end of the build with undefined symbols for SDL (starting with SDL_memcpy).  Might need to investigate the patch more

**Comment by sWski** [comment]
Hello, I was trying to compile Kodi, too. It seems the subset of patches is almost the same as yours, however I am able to compile Kodi from sratch only by running `./build_steamlink.sh`.

You can take a look at my branch [kodi-fixes](/sWski/steamlink-sdk/tree/kodi-fixes/) and provided [readme](/sWski/steamlink-sdk/tree/kodi-fixes/examples/kodi#readme).

**Comment by ezelkow1** [comment]
alright ill see if i can kick off a build today with yours.  I did notice that garbear also seemed to be working on hardware video decode, he had a preliminary patch checked in

**Comment by sWski** [comment]
Yes, I've seen that, haven't tried it though, as it is work in progress. Video decoding works in my Kodi build, however it must be running on CPU.

**Comment by ezelkow1** [comment]
I can confirm build completed successfully with your patches/changes.  So your branch is lookin good, at least much more reliable than mine is at this point

**Comment by jonesmz** [comment]
I was also able to compile sWski's version successfully on a fresh ubuntu 16.04 install (virtual machine) by following sWski's instructions. The resulting build does play at least the video I tried with sound. I'm happy to report that there don't seem to be any problems accessing my Samba server via Kodi. So far everything's working out very nicely!

I notice that Kodi doesn't know how to handle inputs from either the Steam Controller, or the wired XBox 360 controllers. Further, typing from a keyboard into text boxes doesn't work, and instead Kodi needs the user to use the on-screen keyboard (this may just be default Kodi behavior, might have nothing to do with the steamlink sdk).

Finally, trying to install a theme crashes the app, and subsequently the app won't ever finish launching, though I'm afraid I can't recall which theme it was.

**Comment by ezelkow1** [comment]
Interesting. For me the steam controller worked fine, however you have to use the left dpad and use it as a touchpad with a swiping type motion on the dpad. I didnt get to try my kb/m or 360 on it. I also tried a flirc module+ir remote and that also worked perfect out of the box

Im guessing there may be out of memory type issues. I was letting it scan a samba share in the background while doing other things and it just locked up after a few minutes of doing the scan

**Comment by sWski** [comment]
My Steam Controller works, too. For movement is the DPad, analog joystick is working in different scenarios. [Here](https://github.com/sWski/steamlink-sdk/blob/kodi-fixes/examples/kodi/kodi.patch#L52) is the keymap. I've tried Logitech Wireless K400 keyboard and it was working normally, even the touchpad as mouse.

I can try installing themes and inspecting kodi.log. Keep in mind that this "developer preview", there can be libraries that fail to load, etc. 

To stop spamming people here, if you found something specific, you can create an issue in my [repo](https://github.com/sWski/steamlink-sdk), append some explanation or `kodi.log`, which is located in `/home/steam/.kodi/temp` on your Steam Link (you have to [enable ssh](https://github.com/ValveSoftware/steamlink-sdk#ssh-access) access to copy it to your PC).

**Comment by ezelkow1** [comment]
So since you have a working build that seems to work for everyone, do you want to try to do a pull request with your repo? Ill try and close mine (if I can figure it out, still sort of new to working with projects on github)

**Comment by slouken** [comment]
Pulled, thanks!

**Pull request closed without merging**
