### PR TITLE
Improved script

### PR DESCRIPTION
**Pull request by fpscan**

### CODE REVIEW

**Comment by kisak-valve** [comment]
Hello @fpscan, pointing to prebuilt libraries in a third party repository is asking for trouble down the road. This pull request is not acceptable as is.

**Comment by fpscan** [comment]
@kisak-Valve thank you for your quick response, these cores builded with libretro-super and we are hosting this RetroArch package in RetroArch.com until we figure it something else I will be hosting cores into my repo so if it was RetroArch repo you will be okay? Thanks.

**Comment by kisak-valve** [comment]
We'll need to hear from @slouken if that's an acceptable alternative.

Any reason not to add a build target to libretro-super and propose switching over to that like any other supported platform in the project?

**Comment by fpscan** [comment]
> We'll need to hear from @slouken if that's an acceptable alternative.
> 
> Any reason not to add a build target to libretro-super and propose switching over to that like any other supported platform in the project?

This is possible but its above my head, I don't have much knowledge, I am just keeping SteamLink version is up, I haven't asked anyone over there yet but I don't think they can deal with this now. Do you know how can I add target build over there? Thanks.

**Pull request closed without merging**
