### PR TITLE
Added initial fork of RetroArch for Steam Link

### PR DESCRIPTION
**Pull request by anibarro**
Execute the "build_steamlink.sh" script.
Once it's done, you should have the package ready to install in "examples/RetroArch/retroarch-src/steamlink/apps".

Note:
You can create a "roms" folder inside the "RetroArch/retroarch-src" folder and copy some roms for testing before executing the script. They will be added to the package.
Also, if you create a "extra" folder, you can copy compiled cores or any other file and they will also be included.

### CODE REVIEW

**Comment by slouken** [comment]
I updated the build script in the Steam Link SDK repo. Can you check to make sure it still works correctly?

Thanks!

**Comment by anibarro** [comment]
It's much nicer and cleaner!
Just a freetype2 header is not found and GLES2 not detected, which it's mandatory for the cores to work.
Could you add the couple of changes below? After these modifications it's tested and working :)
The readme should be updated as well, with the popd the folders are now different.

```
diff --git a/examples/retroarch/build_steamlink.sh b/examples/retroarch/build_steamlink.sh
index c9a1d47..b03b9f4 100755
--- a/examples/retroarch/build_steamlink.sh
+++ b/examples/retroarch/build_steamlink.sh
@@ -18,7 +18,7 @@ export CPP="${CROSS}cpp"
 export CXX="${CROSS}g++"
 export CFLAGS="--sysroot=$MARVELL_ROOTFS -DLINUX=1 -DEGL_API_FB=1"
 export LDFLAGS="--sysroot=$MARVELL_ROOTFS -static-libgcc -static-libstdc++ -lEGL"
-export INCLUDE_DIRS="-I$MARVELL_ROOTFS/usr/include -I$MARVELL_ROOTFS/usr/include/EGL -I$MARVELL_ROOTFS/usr/include/SDL2 -I${MARVELL_ROOTFS}/include/GLES2"
+export INCLUDE_DIRS="-I$MARVELL_ROOTFS/usr/include -I$MARVELL_ROOTFS/usr/include/EGL -I$MARVELL_ROOTFS/usr/include/SDL2 -I${MARVELL_ROOTFS}/include/GLES2 -I$MARVELL_ROOTFS/usr/include/freetype2"
 export LIBRARY_DIRS="-L$MARVELL_ROOTFS/usr/lib -L$MARVELL_ROOTFS/lib"
 export PKG_CONF_PATH=pkg-config
 
@@ -33,7 +33,7 @@ fi
 # Build it
 #
 pushd "${SRC}"
-./configure --host=$SOC_BUILD --disable-threads --disable-alsa --disable-pulse --enable-neon --disable-shaderpipeline
+./configure --host=$SOC_BUILD --disable-threads --disable-alsa --disable-pulse --enable-neon --disable-shaderpipeline --enable-opengl --enable-opengles
 make $MAKE_J || exit 2
 popd
```

**Comment by slouken** [comment]
That's weird, that change isn't needed for me.

Do you have the change in setenv.sh to set the pkg-config path?

**Comment by anibarro** [comment]
Yes, I did a git clone from scratch for testing but there is at least another user trying to compile, so better wait for his input...

**Comment by parkerlreed** [comment]
It compiled fine for me on 918f267699a86e53e52fd534a729a07eda99441d

Although I haven't tested a core yet.

**Comment by anibarro** [comment]
@parkerlreed can you check the configure lines in the console and check if you get:
`Checking presence of package glesv2 ... 2.0`

**Comment by parkerlreed** [comment]
Ahh yeah I try to start a core and just get that "Paused" that you mentioned. here's the configure log.

````
[parker@e55 retroarch]$ ./build_steamlink.sh 
Cloning into '/home/parker/build/steamlink-sdk/examples/retroarch/retroarch-src'...
remote: Counting objects: 229905, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 229905 (delta 4), reused 0 (delta 0), pack-reused 229889
Receiving objects: 100% (229905/229905), 117.21 MiB | 7.70 MiB/s, done.
Resolving deltas: 100% (171312/171312), done.
~/build/steamlink-sdk/examples/retroarch/retroarch-src ~/build/steamlink-sdk/examples/retroarch
Checking operating system ... Linux (Arch Linux rolling)
Checking for suitable working C compiler ... armv7a-cros-linux-gnueabi-gcc works
Checking for suitable working C++ compiler ... armv7a-cros-linux-gnueabi-g++ works
Checking for pkg-config ... pkg-config
Checking for availability of switch -std=gnu99 in armv7a-cros-linux-gnueabi-gcc ... yes
Checking for availability of switch -Wno-unused-result in armv7a-cros-linux-gnueabi-gcc ... yes
Checking for availability of switch -Wno-unused-variable in armv7a-cros-linux-gnueabi-gcc ... yes
Checking function bcm_host_init in -lbcm_host ... no
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package egl ... 200
Checking function ass_library_init in -lass ... no
Checking function dlopen in -ldl ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking existence of -lminiupnpc ... no
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... no
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... no
Checking presence of package jack >= 0.120.1 ... no
Checking presence of package sdl >= 1.2.10 ... no
Checking presence of package sdl2 >= 2.0.0 ... 2.0.5
Checking presence of package libusb-1.0 >= 1.0.16 ... no
Checking presence of header file GL/gl.h ... no
Notice: Ignoring Cg. Desktop OpenGL is not enabled.
Checking presence of package zlib ... 1.2.3.3
Notice: Not building with threading support. Will skip FFmpeg.
Checking function dlopen in -ldl ... yes
Checking presence of package gbm >= 9.0 ... no
Checking presence of package libdrm ... no
Checking presence of package libxml-2.0 ... no
Checking presence of package vg ... no
Checking existence of -lOpenVG ... no
Checking presence of package libv4l2 ... no
Checking function glFramebufferTexture2D in -lGL ... no
Checking presence of package freetype2 ... 17.4.11
Checking presence of package x11 ... no
Checking presence of package xcb ... no
Checking presence of package wayland-egl ... no
Checking presence of package wayland-cursor ... no
Checking presence of package xkbcommon >= 0.3.2 ... no
Checking presence of package dbus-1 ... 1.8.8
Notice: X11, Xext or xf86vm not present. Skipping X11 code paths.
Checking presence of package libudev ... no
Checking existence of -ludev ... yes
Checking presence of header file linux/parport.h ... yes
Checking presence of header file linux/ppdev.h ... yes
Checking function strlcpy in -lc ... no
Checking function strcasestr in -lc ... yes
Checking function mmap in -lc ... yes
Checking function vkCreateInstance in -lvulkan ... no
Notice: Hardware rendering context not available, XMB, MaterialUI and ZARCH will also be disabled.
Checking presence of predefined macro __ARM_NEON__ ... yes
Notice: Threads are not available, Cheevos will also be disabled.
Notice: Threads are not available, libusb will also be disabled.
Creating make config: config.mk
Creating config header: config.h
CC input/drivers/linuxraw_input.c
CC input/common/linux_common.c
CC input/common/epoll_common.c
CC input/drivers_joypad/linuxraw_joypad.c
CC frontend/drivers/platform_linux.c
````

**Comment by parkerlreed** [comment]
@anibarro Works with your patch

**Comment by anibarro** [comment]
Sweet, let's see if @slouken can confirm

**Comment by parkerlreed** [comment]
@anibarro Also I've noticed something weird. The assets directory is set correctly, I go to Online updater > Update assets, it download fine, stick on 15% extracting, and when it eventually times out and I relaunch it's like nothing ever happened.

**Comment by anibarro** [comment]
I updated the assets while on the xmb menu and also seemed to be stuck, but I went to the kitchen and when I came back, all the icons where in place.
May be trying again?

**Comment by parkerlreed** [comment]
Hmm still no luck. Also oddly enough picodrive stopped launching for me and fceumm just bails out (I swear they were working just a second ago)

**Comment by anibarro** [comment]
I'm using these cores and they all work just fine: https://ufile.io/b01ae

**Comment by slouken** [comment]
There's an issue with file I/O in the home directory, and that should work better in the next Steam Link beta build.

**Comment by parkerlreed** [comment]
Ahh thanks. So that affects all applications in /home/apps? Good to know.

**Comment by parkerlreed** [comment]
@anibarro Question: how are you compiling the cores? Want to take a stab at maybe adapting this to build for the Link

https://github.com/libretro/libretro-super

It can build all the cores (the one's that don't fail compiling that is lol) in one go.

**Comment by anibarro** [comment]
Compiling cores is quite straight forward, but it depends on the core. They either have a configure script or a custom makefile, but you only have to read the variables and config parameters that they use, and provide them with the right environment settings.
You can customize the "setenv.h" adding all the usual variables and then just do a "source [path]/custom_sentenv.sh" before compiling the core.
I will give it a try this weekend if you don't have it by then :)

**Comment by anibarro** [comment]
@parkerlreed I gave it a try and it compiled just "out of the box" (24 cores), no modifications were needed.
I have some extra vars in an extra set_env script though, like:
```
export OS=Linux
export LDFLAGS="--sysroot=$MARVELL_ROOTFS -static-libgcc -static-libstdc++ -lGLESv2 -lSDL2"
export CFLAGS="--sysroot=$MARVELL_ROOTFS -mfpu=neon -marm -mfloat-abi=hard -DLINUX=1 -DEGL_API_FB=1"
export INCLUDE_DIRS="-I$MARVELL_ROOTFS/usr/include -I$MARVELL_ROOTFS/usr/include/EGL -I$MARVELL_ROOTFS/usr/include/SDL2 -I${MARVELL_ROOTFS}/include -I${MARVELL_ROOTFS}/include/sys"
export LIBRARY_DIRS="-L$MARVELL_ROOTFS/usr/lib -L$MARVELL_ROOTFS/lib"
```
They might be needed, so add them if something fails.

I tried a few ones and they all worked, and it was a pleasant surprise to find a "Cave Story" engine!! I played it a lot on my PSP :)

Here is the pack with all the cores, just in case: https://ufile.io/7b9f1

**Pull request merged**
